# Generated by Django 5.0.1 on 2024-02-05 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_edition_book_edition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.FileField(null=True, upload_to='category/'),
        ),
    ]
