# Generated by Django 5.0.1 on 2024-02-05 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_category_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='nb_page',
            field=models.IntegerField(null=True),
        ),
    ]
