# Generated by Django 5.0.1 on 2024-02-07 00:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_book_bookpage_alter_book_coverpage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='bookpage',
            field=models.FileField(default='', upload_to='bookpage/'),
        ),
        migrations.AlterField(
            model_name='book',
            name='coverpage',
            field=models.FileField(default='', upload_to='coverpage/'),
        ),
        migrations.AlterField(
            model_name='book',
            name='edition',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='store.edition'),
        ),
        migrations.AlterField(
            model_name='book',
            name='nb_page',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='book',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
