# Generated by Django 5.0.1 on 2024-02-07 00:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_book_edition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='edition',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='store.edition'),
        ),
    ]
