# Generated by Django 5.0.1 on 2024-02-07 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_remove_book_edition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='coverpage',
            field=models.FileField(upload_to='coverpage/'),
        ),
    ]
