# Generated by Django 5.0.1 on 2024-02-07 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_book_edition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='edition',
        ),
        migrations.DeleteModel(
            name='Edition',
        ),
    ]
