# Generated by Django 5.0.2 on 2024-02-07 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_remove_book_edition_delete_edition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='bookpage',
            field=models.FileField(upload_to='bookpage/'),
        ),
    ]
