# Generated by Django 5.0.2 on 2024-02-07 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_alter_book_bookpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writer',
            name='slug',
            field=models.SlugField(max_length=150),
        ),
    ]
