# Generated by Django 5.0.2 on 2024-02-08 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_history'),
    ]

    operations = [
        migrations.DeleteModel(
            name='History',
        ),
    ]
