# Generated by Django 5.0.2 on 2024-02-08 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='status',
            field=models.CharField(choices=[('En attente', 'En attente'), ('Accepté', 'Accepté'), ('Retourné', 'Retourné')], max_length=100, null=True),
        ),
    ]
