# Generated by Django 5.0.2 on 2024-02-08 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_alter_history_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='created',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='history',
            name='updated',
            field=models.DateTimeField(),
        ),
    ]
