# Generated by Django 5.0.2 on 2024-02-08 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_alter_history_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='updated',
            field=models.DateTimeField(null=True),
        ),
    ]
